trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageTags: '$(Build.BuildId)'
  dockerRegistry: 'mosaik.azurecr.io'

steps:
- task: DockerCompose@0
  displayName: 'docker-compose build'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: 'REGISTRY=$(dockerRegistry)'
    action: 'Build services'
    additionalImageTags: '$(imageTags)'
    includeLatestTag: true
- task: DockerCompose@0
  displayName: 'docker-compose push'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Microsoft Azure Sponsorship(c43f6884-3e86-4d2c-87eb-61b9f5e59d5e)-EventManagement'
    azureContainerRegistry: '{"loginServer":"mosaik.azurecr.io", "id" : "/subscriptions/c43f6884-3e86-4d2c-87eb-61b9f5e59d5e/resourceGroups/rg-shared/providers/Microsoft.ContainerRegistry/registries/mosaik"}'
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: 'REGISTRY=$(dockerRegistry)'
    action: 'Push services'
    additionalImageTags: '$(imageTags)'
    includeLatestTag: true
