version: "3.9"
services:
  backend:
    image: ${REGISTRY:-mosaik}/event-management:${TAG:-latest}
    depends_on:
      - sqlserver
    build: .
    ports:
      - "127.0.0.1:443:443"
    volumes:
      - "./aspnetapp.pfx:/https/aspnetapp.pfx:ro"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging # to seed the database
      ASPNETCORE_URLS: https://0.0.0.0:443
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: secret
      ConnectionStrings__EventManagement: Server=sqlserver;Database=EventManagement;User ID=sa;Password=Start123

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - "127.0.0.1:1433:1433"
    volumes:
      - "mssqldata:/var/opt/mssql/data"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Start123

volumes:
  mssqldata:
